# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Biba.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 515)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 251, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.showContext = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.showContext.setObjectName("showContext")
        self.horizontalLayout_2.addWidget(self.showContext)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(320, 60, 241, 321))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.writeContext = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.writeContext.setObjectName("writeContext")
        self.horizontalLayout_3.addWidget(self.writeContext)
        self.user_permission = QtWidgets.QLineEdit(self.centralwidget)
        self.user_permission.setGeometry(QtCore.QRect(340, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user_permission.setFont(font)
        self.user_permission.setObjectName("user_permission")
        self.readButton = QtWidgets.QPushButton(self.centralwidget)
        self.readButton.setGeometry(QtCore.QRect(340, 390, 75, 31))
        self.readButton.setObjectName("read")
        self.writeButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeButton.setGeometry(QtCore.QRect(430, 390, 75, 31))
        self.writeButton.setObjectName("write")
        self.user = QtWidgets.QLabel(self.centralwidget)
        self.user.setGeometry(QtCore.QRect(10, 20, 54, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user.setFont(font)
        self.user.setObjectName("user")
        self.permission = QtWidgets.QLabel(self.centralwidget)
        self.permission.setGeometry(QtCore.QRect(290, 19, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.permission.setFont(font)
        self.permission.setObjectName("permission")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(60, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.choose = QtWidgets.QPushButton(self.centralwidget)
        self.choose.setGeometry(QtCore.QRect(10, 390, 41, 31))
        self.choose.setObjectName("choose")
        self.filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.filepath.setGeometry(QtCore.QRect(60, 389, 261, 31))
        self.filepath.setObjectName("filepath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        # self.choose.clicked.connect(MainWindow.openFile())
        # self.readButton.clicked.connect(MainWindow.read())
        # self.writeButton.clicked.connect(MainWindow.write())
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_permission.setText(_translate("MainWindow", "B"))
        self.readButton.setText(_translate("MainWindow", "读取"))
        self.writeButton.setText(_translate("MainWindow", "写入"))
        self.user.setText(_translate("MainWindow", "用户："))
        self.permission.setText(_translate("MainWindow", "等级："))
        self.username.setText(_translate("MainWindow", "WSQ"))
        self.choose.setText(_translate("MainWindow", "选择"))
